#include "src/headers/all.h"

#include "src/camera.c"
#include "src/engine.c"
#include "src/file.c"
#include "src/glad.c"
#include "src/input.c"
#include "src/memory.c"
#include "src/os.c"
#include "src/random.c"
#include "src/shader.c"
#include "src/text.c"
#include "src/texture.c"
#include "src/scenes/main_scene.c"

#include "src/main.c"
