#include "headers/all.h"

#include "camera.c"
#include "engine.c"
#include "file.c"
#include "glad.c"
#include "input.c"
#include "locale.c"
#include "memory.c"
#include "os.c"
#include "random.c"
#include "shader.c"
#include "text.c"
#include "texture.c"
#include "particles.c"
#include "sound.c"
#include "options.c"
#include "framebuffer.c"
#include "tilemap.c"
#include "sprite.c"
#include "shapes.c"
#include "primitives.c"
#include "buffer.c"
#include "scenes/main_scene.c"

#include "std.c"
#include "main.c"
